From stdpp Require Import prelude.

Context `{c : THIS_CLASS_DOESNT_EXIST_BUT_NO_ERROR}.

Check THIS_CLASS_DOESNT_EXIST_BUT_NO_ERROR.
(* ===> THIS_CLASS_DOESNT_EXIST_BUT_NO_ERROR : Type *)

Print THIS_CLASS_DOESNT_EXIST_BUT_NO_ERROR.
(* *** [ THIS_CLASS_DOESNT_EXIST_BUT_NO_ERROR : Type ] *)